1c1,8
< FROM alpine:3.6
---
> ARG target=arm32v6
> FROM $target/alpine
> 
> ARG arch=arm
> ENV ARCH=$arch
> 
> # Trick docker build in case qemu binary is not in dir.
> COPY .blank tmp/qemu-$ARCH-static* /usr/bin/
5c12
< COPY dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
---
> COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
15d21
<      curl https://dl.minio.io/server/minio/release/linux-amd64/minio > /usr/bin/minio && \
