--- Dockerfile.release  2018-03-16 18:42:08.826857054 -0500
+++ Dockerfile.release.arm      2018-03-16 18:43:53.667517915 -0500
@@ -1,8 +1,15 @@
-FROM alpine:3.6
+ARG target=arm32v6
+FROM $target/alpine
+
+ARG arch=arm
+ENV QEMU_ARCH=$arch
+
+# Trick docker build in case qemu binary is not in dir.
+COPY .blank qemu-$QEMU_ARCH-static* /usr/bin/

 MAINTAINER Minio Inc <dev@minio.io>

-COPY dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
+COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/

 ENV MINIO_UPDATE off
 ENV MINIO_ACCESS_KEY_FILE=access_key \
@@ -12,7 +19,6 @@
      apk add --no-cache ca-certificates && \
      apk add --no-cache --virtual .build-deps curl && \
      echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
-     curl https://dl.minio.io/server/minio/release/linux-amd64/minio > /usr/bin/minio && \
      chmod +x /usr/bin/minio  && \
      chmod +x /usr/bin/docker-entrypoint.sh && \
      chmod +x /usr/bin/healthcheck.sh
